### PR TITLE
Fixed greasemonkey support

### PR DESCRIPTION
**Pull request by neon-kite-creature**
Fixed reference to associds in greasemonkey

### CODE REVIEW

**Comment by neon-kite-creature** [comment]
Fix tested on Firefox with both Greasemonkey and Tampermonkey and on Chromium-based Edge with Tampermonkey.

**Comment by likuilin** [comment]
Thank you for the pull request! I wonder, are other things that access window properties also broken in the same way? For example, the script assigns window.goToReddit, goToFacebook, etc for the buttons on the page, injected by building HTML as a string (something questionable) to use. Or does it only apply to things read from window by the script?

**Comment by neon-kite-creature** [comment]
Just noticed, all nav-bar buttons (including help) are broken in Firefox-Greasemonkey, but Technical details all display as expected

**Comment by likuilin** [comment]
Yea, that's what I figured. 

I'll do some more testing when I'm next at a computer. Most likely, the best way to actually fix this is to audit all window object uses and refactor to do that the right way. Including switching to document.createElement instead of building HTML as a string, so we can directly attach an event listener to it with a local callback, and whatnot, before adding it to the DOM. 

Or, alternatively, we could just say whatever and s/window/unsafeWindow. That also would work, I guess. Worse solution though.

**Comment by neon-kite-creature** [comment]
> 
> 
> Thank you for the pull request! I wonder, are other things that access window properties also broken in the same way? For example, the script assigns window.goToReddit, goToFacebook, etc for the buttons on the page, injected by building HTML as a string (something questionable) to use. Or does it only apply to things read from window by the script?

window.goToReddit and similar functions aren't defined according to Firefox-Greasemonkey

**Comment by likuilin** [comment]
If you would like to fix this the "right way" by refactoring it so it attaches its own event listeners to components and whatnot, by all means go ahead, I'll review a subsequent pull request. 

However, it's a lot of work, and I don't think it is necessary, because the script requires no privileged resources, and, even if it did, the unsafe part of it is limited to a malicious Dan updating his website to take advantage of people with this script installed.

**Pull request closed without merging**
